title: Bluetooth Proxy Stick by SmartHomeGuys
description: Bluetooth Proxy USB Stick for Home Assistant (no cable needed)

remote_theme: pages-themes/slate@v0.2.0

plugins:
- jekyll-remote-theme

#url: https://smarthomeguys.github.io
