title: SmartHomeGuys - Bluetooth Proxy Stick
description: SmartHomeGuys Bluetooth Proxy Stick Documentation

remote_theme: pages-themes/slate@v0.2.0
#remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

#url: https://smarthomeguys.github.io
