title: Bluetooth Proxy Stick
description: A Bluetooth Proxy USB Stick for Home Assistant that needs no cable

remote_theme: pages-themes/slate@v0.2.0

plugins:
- jekyll-remote-theme

#url: https://smarthomeguys.github.io
