title: SmartHomeGuys Bluetooth Proxy Stick Documentation
description: Documentation for the SmartHomeGuys Bluetooth Proxy Stick

remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme

#url: https://smarthomeguys.github.io
